global.savedata_async_id = -1;
global.savedata_async_load = false;
snd_play(snd_error);
is_active = true;
global.savedata_pause = true;
font_face = (global.lang == "en") ? 3 : 10;
scale = 2;
type = "default";
error_type = "save_failed";
text_save_data_corrupt = (global.lang == "en") ? "（发现损坏的存档数据。）" : "(セーブデータが#破損しています)";
text_temp_save_failed = (global.lang == "en") ? "（保存临时#数据失败。）" : "(一時データを#セーブできませんでした)";
text_save_failed = (global.lang == "en") ? "（存档数据#写入失败。）" : "(セーブデータを#書き込めませんでした)";
window_text = text_save_failed;
auto_timer = 0;
choice_index = 0;
