function scr_credit(arg0, arg1, arg2 = 1) constructor
{
    header = arg0;
    text_line = arg1;
    columns = arg2;
}

function generate_credits()
{
    var credits = [];
    credits[0] = [new scr_credit([stringsetloc("-Main Artist-", "scr_credit_slash_scr_credit_gml_18_0"), stringsetloc("-Main Animator-", "scr_credit_slash_scr_credit_gml_19_0")], [stringset("Temmie Chang")])];
    credits[1] = [new scr_credit([stringsetloc("-Main Team-", "scr_credit_slash_scr_credit_gml_29_0")], [stringset("Sarah O'Donnell"), stringset("Juju (Taxiderby)"), stringset("Fred Wood"), stringset("Jean Canellas"), stringset("AlexMdle"), stringset("PureQuestion"), stringsetloc("Robert Sephazon (Producer)", "scr_credit_slash_scr_credit_gml_38_0")])];
    credits[2] = [new scr_credit([stringsetloc("-BG Concept Art-", "scr_credit_slash_scr_credit_gml_44_0")], [stringsetloc("(Original Board 1,2,3 Concept)", "scr_credit_slash_scr_credit_gml_47_0"), stringset("Gigi DG"), stringsetloc("(Teevie World)", "scr_credit_slash_scr_credit_gml_49_0"), stringset("Tcheska Lynn B (chess)")]), new scr_credit([stringsetloc("-Costume Design-", "scr_credit_slash_scr_credit_gml_54_0")], [stringsetloc("Gigi DG", "scr_credit_slash_scr_credit_gml_57_0")])];
    credits[3] = [new scr_credit([stringsetloc("-Guest Character Design-", "scr_credit_slash_scr_credit_gml_64_0")], [stringsetloc("(Lancer, Rudinn, Hathy)", "scr_credit_slash_scr_credit_gml_67_0"), stringsetloc("(Clover, King, Jevil)", "scr_credit_slash_scr_credit_gml_68_0"), stringset("Kanotynes")]), new scr_credit([stringsetloc("-Singing This Song-", "scr_credit_slash_scr_credit_gml_73_0")], [stringset("Laura Shigihara")])];
    credits[4] = [new scr_credit([stringsetloc("-Guest Character Design-", "scr_credit_slash_scr_credit_gml_83_0")], [stringsetloc("(Lanino, Elnina)", "scr_credit_slash_scr_credit_gml_86_0"), stringset("NELNAL")]), new scr_credit([stringsetloc("-Photoshop Edits & Weird Anim-", "scr_credit_slash_scr_credit_gml_98_0")], [stringset("Everdraed")])];
    credits[5] = [new scr_credit([stringsetloc("-Pixel Art Assistance-", "scr_credit_slash_scr_credit_gml_108_0")], [stringset("Samanthuel Gillson (splendidland)"), stringset("Shawn (puppiesandanime)"), stringset("Kenju"), stringset("Tcheska Lynn B (chess)"), stringset("Satoshi Maruyama")]), new scr_credit([stringsetloc("-Development Tools (Cool)-", "scr_credit_slash_scr_credit_gml_119_0")], [stringset("Juju Adams")])];
    credits[6] = [new scr_credit([stringsetloc("-3D Assets, Anim, Posing-", "scr_credit_slash_scr_credit_gml_129_0")], [stringset("Chelsea Saunders (pixelatedcrown)")]), new scr_credit([stringsetloc("-3D Tenna Pixel Cleanup-", "scr_credit_slash_scr_credit_gml_136_0")], [stringset("Clairevoire")]), new scr_credit([stringsetloc("-Cutscene Assistance-", "scr_credit_slash_scr_credit_gml_143_0")], [stringset("Tcheska Lynn B (chess)")])];
    credits[7] = [new scr_credit([stringsetloc("-Chef Minigame Program-", "scr_credit_slash_scr_credit_gml_153_0")], [stringset("ondydev")]), new scr_credit([stringsetloc("-Cowboy Program & Other Detail-", "scr_credit_slash_scr_credit_gml_160_0")], [stringset("James Begg")]), new scr_credit([stringsetloc("-Tenna VHS Final Scene Assist-", "scr_credit_slash_scr_credit_gml_167_0")], [stringset("Smallbu Animation")]), new scr_credit([stringsetloc("-Additional Puzzle Design-", "scr_credit_slash_scr_credit_gml_174_0")], [stringset("NamaTakahashi")])];
    credits[8] = [new scr_credit([stringsetloc("-Japanese Localization-", "scr_credit_slash_scr_credit_gml_170_0")], [stringsetloc("8-4, Ltd.", "scr_credit_slash_scr_credit_gml_173_0")]), new scr_credit([stringsetloc("-Translator-", "scr_credit_slash_scr_credit_gml_177_0")], [stringset("yzdnn，晨忆风谷，玖颜332(teniver) \n 单衫_石宇砖，米粒(enderesting)，凝雨白沙 \n 便利贴不翘边，夕葵，YiTang")])];
    credits[9] = [new scr_credit([stringsetloc("-Localization Producers-", "scr_credit_slash_scr_credit_gml_187_0")], [stringset("鸥皇不欧，AX暗星233，单衫_石宇砖 \n 瓦斯霓特·洋芋，Neubulae[Almona] \n Uni，瑶玲，夕葵，鼠球，FH丶CY \n wiike，Cupcake~，yzdnn，Mercurypie \n 凝雨白沙，旋风SELF，就是菜刀 \n 丢丢hamburger，Felixeffe，一瓶洋酒 \n JH，w1n1n1t351，onomi，无辣味wdw \n\n\n Orlighto，Ralsei，西乡小男孩 \n 云凝沙，Pines_z，Mr_H2T，ALoss"), stringset("")]), new scr_credit([stringsetloc("-Localization Support-", "scr_credit_slash_scr_credit_gml_195_0")], [stringset(""), stringset(""), stringset(""), stringset(""), stringset("")])];
    credits[10] = [new scr_credit([stringsetloc("-Platform Programming-", "scr_credit_slash_scr_credit_gml_207_0")], [stringset("Sarah O'Donnell"), stringset("Henri Beeres (Enjl)")]), new scr_credit([stringsetloc("-Programming Support-", "scr_credit_slash_scr_credit_gml_214_0")], [stringset("Gregg Tavares")]), new scr_credit([stringsetloc("-Japanese Graphics-", "scr_credit_slash_scr_credit_gml_221_0")], [stringset("256graph"), stringset("Satoshi Maruyama")])];
    credits[11] = [new scr_credit([stringsetloc("-QA-", "scr_credit_slash_scr_credit_gml_231_0"), stringsetloc("DIGITAL HEARTS Co., Ltd.", "scr_credit_slash_scr_credit_gml_234_0")], [stringset("Yoshikazu Hironaka"), stringset("Riku Shimizu"), stringset("Akira Ishiki"), stringset("Hidemi Miyauchi"), stringset("Kazutaka Kawahara"), stringset("Yuta Nishimura"), stringset("Daisuke Nakaie"), stringset("Shinji Yasue"), stringset("Taishi Mukaigawara"), stringset("Hiromasa Tokida"), stringset("Yuki Takeuchi"), stringset("Yu Takamori"), stringset("Yuta Doi"), stringset("Yuki Wada"), stringset("Satoru Watanuki"), stringset("Monami Katayama")], 2)];
    credits[12] = [new scr_credit([stringsetloc("-Super Tester-", "scr_credit_slash_scr_credit_gml_245_0")], [stringset("Esteban Criado (DruidVorse)")]), new scr_credit([stringsetloc("-Website-", "scr_credit_slash_scr_credit_gml_253_0")], [stringset("Brian Coia")])];
    credits[13] = [new scr_credit([stringsetloc("-Trailers & All Video Editing-", "scr_credit_slash_scr_credit_gml_277_0")], [stringset("Everdraed")]), new scr_credit([stringsetloc("-Tenna's Typography and Logos-", "scr_credit_slash_scr_credit_gml_91_0")], [stringset("Audrey Waner")])];
    credits[14] = [new scr_credit([stringsetloc("-Special Thanks-", "scr_credit_slash_scr_credit_gml_287_0")], [stringset("Hiroko Minamoto"), stringset("Graeme Howard"), stringset("Yutaka Sato (Happy Ruika)"), stringsetloc("All 8-4 & Fangamer Staff", "scr_credit_slash_scr_credit_gml_293_0"), stringset("Claire & Andrew"), stringset("Brian Lee"), stringset("YoYo Games")])];
    return credits;
}
